"""
neo4j_store.py — persist the equipment-level plant graph to Neo4j
(handoff item 4: "load the gated graph to Neo4j").

Two ways in, one graph model, same input shape as `adapter.py` output:

  * to_cypher(graph) -> str    pure offline Cypher script (idempotent
                               MERGEs) — paste into Neo4j Browser or pipe
                               to cypher-shell; zero dependencies, unit-
                               testable without a server
  * load(graph, ...)           live batched load (UNWIND per equipment
                               type) via the optional `neo4j` driver;
                               inject a fake driver for tests

Graph model
-----------
Every terminal becomes (:PlantItem:<Type> {tag, name, equipment_type,
detection_confidence, sheets, ...}) with `tag` unique. Connections split
by direction confidence, mirroring the direction-aware L3 reasoner:

  known    -> (source)-[:FLOWS_TO {line_numbers, direction_sources}]->(target)
              the relationship direction IS the verified flow direction
  other    -> (a)-[:CONNECTED_TO {direction, direction_note?, ...}]->(b)
              drawing order, NOT flow — treat as undirected in queries

so `-[:FLOWS_TO*]->` is always a verified flow traversal, and plain
connectivity questions match both types with no direction arrow.
"""

from __future__ import annotations

import json
from collections import defaultdict

# equipment_type -> extra node label (PascalCase); single words capitalize
_MULTIWORD_LABEL = {
    "check_valve": "CheckValve",
    "relief_valve": "ReliefValve",
    "control_valve": "ControlValve",
    "heat_exchanger": "HeatExchanger",
}

# adapter attribute keys renamed to avoid clashing with Neo4j concepts
_RENAME = {"labels": "opc_labels"}


def _label(equipment_type: str) -> str:
    return _MULTIWORD_LABEL.get(equipment_type, equipment_type.capitalize())


def _lit(value) -> str:
    """A Cypher literal. JSON is valid Cypher for strings, numbers,
    booleans and flat lists — which is all the adapter emits."""
    return json.dumps(value, ensure_ascii=False)


def _map(props: dict) -> str:
    """A Cypher map literal; keys are known-safe identifiers."""
    return "{" + ", ".join(f"{k}: {_lit(v)}" for k, v in props.items()) + "}"


def _node_props(node: dict) -> dict:
    props = {
        "tag": node["tag"],
        "name": node["name"],
        "equipment_type": node["equipment_type"],
        "detection_confidence": node["detection_confidence"],
    }
    for key, value in node.get("attributes", {}).items():
        if value not in (None, "", []):
            props[_RENAME.get(key, key)] = value
    return props


def _rel(edge: dict) -> tuple[str, dict]:
    attrs = edge.get("attributes", {})
    direction = attrs.get("direction", "unknown")
    props = {}
    if attrs.get("line_numbers"):
        props["line_numbers"] = attrs["line_numbers"]
    if edge.get("line_tag"):
        props["line_tag"] = edge["line_tag"]
    if direction == "known":
        rtype = "FLOWS_TO"
        if attrs.get("direction_sources"):
            props["direction_sources"] = attrs["direction_sources"]
    else:
        rtype = "CONNECTED_TO"
        props["direction"] = direction  # "unknown" (or "conflict")
        if attrs.get("direction_note"):
            props["direction_note"] = attrs["direction_note"]
    return rtype, props


CONSTRAINT = ("CREATE CONSTRAINT plant_item_tag IF NOT EXISTS "
              "FOR (n:PlantItem) REQUIRE n.tag IS UNIQUE")


def to_cypher(graph: dict) -> str:
    """Full idempotent Cypher script for the graph (constraint, nodes,
    relationships). Safe to run repeatedly."""
    lines = [
        "// 2401 plant graph — generated by plant_graph.neo4j_store",
        "// FLOWS_TO = verified flow direction; CONNECTED_TO = drawing "
        "order only",
        CONSTRAINT + ";",
    ]
    for node in graph["nodes"]:
        props = _node_props(node)
        lines.append(
            f"MERGE (n:PlantItem {{tag: {_lit(props['tag'])}}}) "
            f"SET n:{_label(node['equipment_type'])}, n += {_map(props)};")
    for edge in graph["edges"]:
        rtype, props = _rel(edge)
        set_clause = f" SET r += {_map(props)}" if props else ""
        lines.append(
            f"MATCH (a:PlantItem {{tag: {_lit(edge['source'])}}}), "
            f"(b:PlantItem {{tag: {_lit(edge['target'])}}}) "
            f"MERGE (a)-[r:{rtype}]->(b){set_clause};")
    return "\n".join(lines) + "\n"


def _chunks(rows: list, size: int):
    for i in range(0, len(rows), size):
        yield rows[i:i + size]


def load(graph: dict, uri: str = "bolt://localhost:7687",
         user: str = "neo4j", password: str | None = None,
         database: str = "neo4j", batch_size: int = 500,
         driver=None) -> dict:
    """Batched live load. Returns {"nodes": n, "relationships": m}.

    The `neo4j` driver import is deferred so offline installs never need
    it; pass `driver` to inject one (tests use a fake)."""
    owns_driver = driver is None
    if driver is None:
        from neo4j import GraphDatabase  # optional dependency
        driver = GraphDatabase.driver(uri, auth=(user, password))
    try:
        with driver.session(database=database) as session:
            session.run(CONSTRAINT)

            nodes_by_label: dict[str, list] = defaultdict(list)
            for node in graph["nodes"]:
                nodes_by_label[_label(node["equipment_type"])].append(
                    _node_props(node))
            n_nodes = 0
            for label, rows in sorted(nodes_by_label.items()):
                for chunk in _chunks(rows, batch_size):
                    session.run(
                        f"UNWIND $rows AS row "
                        f"MERGE (n:PlantItem {{tag: row.tag}}) "
                        f"SET n:{label}, n += row",
                        rows=chunk)
                    n_nodes += len(chunk)

            rels_by_type: dict[str, list] = defaultdict(list)
            for edge in graph["edges"]:
                rtype, props = _rel(edge)
                rels_by_type[rtype].append({
                    "source": edge["source"],
                    "target": edge["target"],
                    "props": props,
                })
            n_rels = 0
            for rtype, rows in sorted(rels_by_type.items()):
                for chunk in _chunks(rows, batch_size):
                    session.run(
                        f"UNWIND $rows AS row "
                        f"MATCH (a:PlantItem {{tag: row.source}}), "
                        f"(b:PlantItem {{tag: row.target}}) "
                        f"MERGE (a)-[r:{rtype}]->(b) SET r += row.props",
                        rows=chunk)
                    n_rels += len(chunk)
        return {"nodes": n_nodes, "relationships": n_rels}
    finally:
        if owns_driver:
            driver.close()
